#!/usr/bin/python3
def raise_exception():
    print('{:d}'.format([1, 3, 4, 5]))
